---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: octopus
  namespace: demo
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: glob:3.1.1-debian-9-*
spec:
  releaseName: octopus
  chart:
    git: ssh://git@github.com/ronaldcrb/flux-get-started
    ref: master
    path: charts/octopus
  